### ISSUE TITLE
Does not work on DeNo 1.2

### ISSUE THREAD

**Issue by osorito** [halvardssm/oak-middleware-jwt#1]
**Describe the bug**
Hello i'm using

deno 1.2.0
v8 8.5.216
typescript 3.9.2

**To Reproduce**
When I call just the imports 

// @ts-ignore`
import { jwtMiddlewareRouter } from "https://raw.githubusercontent.com/halvardssm/oak-middleware-jwt/master/mod.ts"

// @ts-ignore
import { Router,RouterMiddleware } from 'https://deno.land/x/oak/mod.ts';`

`error: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@0.51.0/path/win32.ts:911:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@0.51.0/path/posix.ts:433:18

TS2305 [ERROR]: Module '"https://raw.githubusercontent.com/halvardssm/oak-middleware-jwt/master/mod"' has no exported member 'jwtMiddlewareRouter'.
import { jwtMiddlewareRouter } from "https://raw.githubusercontent.com/halvardssm/oak-middleware-jwt/master/mod.ts"
         ~~~~~~~~~~~~~~~~~~~
    at file:///Users/omar/DeNo/sec25DeNo/routes/feed.ts:1:10

Found 3 errors.`

**Expected behavior**
A clear and concise description of what you expected to happen.
I just want to use jwt with oak to validate the token sent from the front end to make sure it's a valid user.

**Screenshots or error log**
If applicable, add screenshots or error log to help explain your problem.

**System (please complete the following information):**

- OS: Mac OSX Catalina
10.15.6
- Deno version [e.g. 1.0.0]
1.2.0
- Module version [e.g. 1.0.0]

deno 1.2.0
v8 8.5.216
typescript 3.9.2

**Additional context**
Add any other context about the problem here.

**Comment by halvardssm** [comment]
Hi @osorito ! Great that you caught this bug! I just made a release (v4.0.0) could you let me know if using this version fixed your issue?

**Comment by osorito** [comment]
Just with the headers and --reload option the code compiles.

The arguments for onSuccess they don't have a type so you get this error.
`error: TS2344 [ERROR]: Type 'RouterMiddleware<Record<string | number, string | undefined>, Record<string, any>>' does not satisfy the constraint 'RouterMiddleware<Record<string | number, string | undefined>, Record<string, any>> | Middleware<Record<string, any>, Context<Record<string, any>>>'.
  Type 'import("https://deno.land/x/oak/router").RouterMiddleware<Record<string | number, string | undefined>, Record<string, any>>' is not assignable to type 'import("https://deno.land/x/oak@v6.0.1/router").RouterMiddleware<Record<string | number, string | undefined>, Record<string, any>>'.
    Types of parameters 'context' and 'context' are incompatible.
      Type 'import("https://deno.land/x/oak@v6.0.1/router").RouterContext<Record<string | number, string | undefined>, Record<string, any>>' is not assignable to type 'import("https://deno.land/x/oak/router").RouterContext<Record<string | number, string | undefined>, Record<string, any>>'.
        Types of property 'matched' are incompatible.
          Type 'Layer<Record<string | number, string | undefined>, Record<string, any>>[] | undefined' is not assignable to type 'Layer<Record<string | number, string | undefined>, Record<string, any>>[] | undefined'. Two different types with this name exist, but they are unrelated.
            Type 'Layer<Record<string | number, string | undefined>, Record<string, any>>[]' is not assignable to type 'Layer<Record<string | number, string | undefined>, Record<string, any>>[]'. Two different types with this name exist, but they are unrelated.
              Type 'Layer<Record<string | number, string | undefined>, Record<string, any>>' is not assignable to type 'Layer<Record<string | number, string | undefined>, Record<string, any>>'. Two different types with this name exist, but they are unrelated.
                Property '#opts' in type 'Layer' refers to a different member that cannot be accessed from within type 'Layer'.
router.get('/feed/posts',jwtMiddleware<RouterMiddleware>({ key:JWT_KEY as string, onSuccess }),getPost);`

If I try to manually set them manually like this
`const onSuccess: OnSuccessHandler = (ctx:any, token:any) => {
    ctx.state.userId = token
    console.log(`this test ${token}`);
  }
`
I get this error
`
error: TS2344 [ERROR]: Type 'RouterMiddleware<Record<string | number, string | undefined>, Record<string, any>>' does not satisfy the constraint 'RouterMiddleware<Record<string | number, string | undefined>, Record<string, any>> | Middleware<Record<string, any>, Context<Record<string, any>>>'.
  Type 'import("https://deno.land/x/oak/router").RouterMiddleware<Record<string | number, string | undefined>, Record<string, any>>' is not assignable to type 'import("https://deno.land/x/oak@v6.0.1/router").RouterMiddleware<Record<string | number, string | undefined>, Record<string, any>>'.
    Types of parameters 'context' and 'context' are incompatible.
      Type 'import("https://deno.land/x/oak@v6.0.1/router").RouterContext<Record<string | number, string | undefined>, Record<string, any>>' is not assignable to type 'import("https://deno.land/x/oak/router").RouterContext<Record<string | number, string | undefined>, Record<string, any>>'.
        Types of property 'matched' are incompatible.
          Type 'Layer<Record<string | number, string | undefined>, Record<string, any>>[] | undefined' is not assignable to type 'Layer<Record<string | number, string | undefined>, Record<string, any>>[] | undefined'. Two different types with this name exist, but they are unrelated.
            Type 'Layer<Record<string | number, string | undefined>, Record<string, any>>[]' is not assignable to type 'Layer<Record<string | number, string | undefined>, Record<string, any>>[]'. Two different types with this name exist, but they are unrelated.
              Type 'Layer<Record<string | number, string | undefined>, Record<string, any>>' is not assignable to type 'Layer<Record<string | number, string | undefined>, Record<string, any>>'. Two different types with this name exist, but they are unrelated.
                Property '#opts' in type 'Layer' refers to a different member that cannot be accessed from within type 'Layer'.
router.get('/feed/posts',jwtMiddleware<RouterMiddleware>({ key:JWT_KEY as string, onSuccess }),getPost);`

**Comment by halvardssm** [comment]
Sorry that I haven't gotten back to you in some days, I am in the middle of a vacation at the moment 😄 

I will have a closer look on Thursday, do you have a repo I can look at?

**Comment by halvardssm** [comment]
@osorito Did your issue get solved?

**Comment by osorito** [comment]
Yes, I used the djwt directly.
