### ISSUE TITLE
Please update to latest djwt release

### ISSUE THREAD

**Issue by timonson** [halvardssm/oak-middleware-jwt#3]
Sorry for the inconvenience @halvardssm, I know you just updated this repo! But this will be the last breaking change of the API in `djwt`.
The change I am referring to is that `setExpiration` takes seconds instead of millisecond as argument now. Here is the latest release: https://github.com/timonson/djwt/releases/tag/v1.1
Thank you very much!

Edit: new release: https://github.com/timonson/djwt/releases/tag/v1.2

**Comment by halvardssm** [comment]
No worries! Thanks for letting me know! Will get cracking on this on Thursday most likely, unless someone submits a pr 👍

**Comment by halvardssm** [comment]
Finally got some time on my hands 💪
